server:
  port: 8062

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: customer-service-route
          uri: lb://customer-service
          predicates:
            - Path=/api/customers/**
        - id: recharge-service-route
          uri: lb://recharge-service
          predicates:
            - Path=/api/recharges/**
        - id: processing-service-route
          uri: lb://processing-service
          predicates:
            - Path=/api/transactions/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8061/eureka

springdoc:
  swagger-ui:
    path: /swagger-ui.html

