spring:
  application:
    name: customer-service
  config:
    import: optional:configserver:http://localhost:8060

server:
  port: 8063

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true


