spring:
  application:
    name: eureka-server

  config:
    import: optional:configserver:http://localhost:8060

server:
  port: 8061

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

